[package]
name = "login"
version = "0.1.0"
authors = ["Dekel Yigal <dekelyi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
